#!/bin/bash

if [ -f host.env ]; then
        . host.env
fi

if [ -z $DOCUMENT_ROOT ] ; then
        DOCUMENT_ROOT="/opt/ffx/"
fi

FOLDER_TMUX="/etc/tmux.d"
FOLDER_DOCKER_SYSTCL="/etc/systemd/system/docker.service.d"

FOLDER_LIST="$FOLDER_TMUX $FOLDER_DOCKER_SYSTCL $DOCUMENT_ROOT"

for i in $FOLDER_LIST ; do
        if [ ! -d $i ] ; then
                mkdir -p $i
        fi
done

# Root configuration
perl -pi -e 's/^PermitRootLogin.*$/PermitRootLogin yes/g' /etc/ssh/sshd_config
perl -pi -e 's/^CONSOLE=/#CONSOLE=/g' /etc/default/login
rolemod -K type=normal root
svcadm restart svc:/network/ssh:default

echo 'HISTFILE=$HOME/.histfile/`date "+%Y-%m-%d-%T"`' >> /root/.profile
echo 'export HISTFILE' >> /root/.profile
echo 'HISTTIMEFORMAT="%h/%m - %H:%M:%S "' >> /root/.profile
echo 'export HISTTIMEFORMAT' >> /root/.profile
echo 'history -s `who am i`' >> /root/.profile
mkdir -p $HOME/.histfile

# LC env configuration
svccfg -s svc:/system/environment:init setprop environment/LANG = astring: en_US.ISO8859-15
#svccfg -s svc:/system/environment:init setprop environment/LC_ALL = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_ALL = astring: en_US.UTF-8
svccfg -s svc:/system/environment:init setprop environment/LC_CTYPE = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_NUMERIC = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_TIME = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_COLLATE = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_MONETARY = astring: en_US.ISO8859-1
svccfg -s svc:/system/environment:init setprop environment/LC_MESSAGES = astring: C
svcadm refresh svc:/system/environment

# DNS configuration
for i in password group network protocol rpc ether netmask bootparam publickey automount alias service project auxth_attr prof_attr tnrhtp tnrhdb  ; do
	svccfg -s svc:/system/name-service/switch setprop config/$i = astring: \"files ldap\"
done

svccfg -s name-service/switch setprop config/host = astring: \"files dns\"
svcadm refresh name-service/switch

#TCP/UDP settings :
ipadm set-prop -p send_buf=1048576 tcp
ipadm set-prop -p recv_buf=1048576 tcp
ipadm set-prop -p max_buf=104857600 tcp
ipadm set-prop -p _cwnd_max=5242880 tcp
ipadm set-prop -p _conn_req_max_q=10240 tcp
ipadm set-prop -p _conn_req_max_q0=10240 tcp
ipadm set-prop -p recv_buf=65535 udp
ipadm set-prop -p send_buf=65535 udp
ipadm set-prop -p max_buf=4194304 udp

# Package installation
pkg install tmux
pkg install system/font/xorg/iso8859-4 system/font/xorg/iso8859-5 system/font/xorg/iso8859-7 system/font/xorg/iso8859-8 system/font/xorg/iso8859-9
